import Head from 'next/head'

import LandingLayout from 'components/landing/layout'
import { Features, Hero } from 'components/landing'
import { LandingPageDetails } from 'public/LandingDeatils'

const Landing = () => {
  return (
    <>
      <Head>
        <title>Green Investing</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero {...LandingPageDetails.Hero} />
      <Features {...LandingPageDetails.Features} />
    </>
  )
}

Landing.getLayout = LandingLayout

export default Landing
