export const ESGDataSet = [
  {
    esg_id: 502,
    company_name: 'Apple Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'AAPL',
    environment_grade: 'BBB',
    environment_level: 'Medium',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'BB',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '02-10-2021',
    environment_score: 355,
    social_score: 275,
    governance_score: 255,
    total: 885
  },
  {
    esg_id: 4720,
    company_name: 'Microsoft Corporation',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'MSFT',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'B',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '26-09-2021',
    environment_score: 500,
    social_score: 209,
    governance_score: 200,
    total: 909
  },
  {
    esg_id: 305,
    company_name: 'Alphabet Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'GOOGL',
    environment_grade: 'BBB',
    environment_level: 'Medium',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '02-10-2021',
    environment_score: 338,
    social_score: 269,
    governance_score: 348,
    total: 955
  },
  {
    esg_id: 70870,
    company_name: 'Alphabet Inc',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'GOOG',
    environment_grade: 'B',
    environment_level: 'Medium',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BB',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '30-09-2021',
    environment_score: 200,
    social_score: 264,
    governance_score: 330,
    total: 794
  },
  {
    esg_id: 342,
    company_name: 'Amazon.com, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'AMZN',
    environment_grade: 'AA',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'A',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '02-10-2021',
    environment_score: 683,
    social_score: 357,
    governance_score: 315,
    total: 1355
  },
  {
    esg_id: 2664,
    company_name: 'Facebook, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'FB',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '12-09-2021',
    environment_score: 500,
    social_score: 331,
    governance_score: 310,
    total: 1141
  },
  {
    esg_id: 7009,
    company_name: 'Tesla, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'TSLA',
    environment_grade: 'AA',
    environment_level: 'Medium',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '14-09-2021',
    environment_score: 603,
    social_score: 265,
    governance_score: 265,
    total: 1133
  },
  {
    esg_id: 5244,
    company_name: 'NVIDIA Corporation',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'NVDA',
    environment_grade: 'BBB',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'BB',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-09-2021',
    environment_score: 313,
    social_score: 300,
    governance_score: 275,
    total: 888
  },
  {
    esg_id: 3655,
    company_name: 'IDEXX Laboratories, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'IDXX',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '12-09-2021',
    environment_score: 473,
    social_score: 330,
    governance_score: 305,
    total: 1108
  },
  {
    esg_id: 3865,
    company_name: 'Intuitive Surgical, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'ISRG',
    environment_grade: 'B',
    environment_level: 'Medium',
    social_grade: 'B',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'B',
    total_level: 'Medium',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-09-2021',
    environment_score: 230,
    social_score: 205,
    governance_score: 205,
    total: 640
  },
  {
    esg_id: 448,
    company_name: 'Analog Devices, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'ADI',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '02-10-2021',
    environment_score: 451,
    social_score: 366,
    governance_score: 293,
    total: 1110
  },
  {
    esg_id: 4714,
    company_name: 'Microchip Technology Incorporated',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'MCHP',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'B',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-09-2021',
    environment_score: 500,
    social_score: 218,
    governance_score: 270,
    total: 988
  },
  {
    esg_id: 5510,
    company_name: 'PayPal Holdings, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'PYPL',
    environment_grade: 'BBB',
    environment_level: 'Medium',
    social_grade: 'B',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'BB',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-09-2021',
    environment_score: 370,
    social_score: 218,
    governance_score: 295,
    total: 883
  },
  {
    esg_id: 614,
    company_name: 'ASML Holding N.V.',
    exchange_symbol: 'XAMS',
    stock_symbol: 'ASML',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '02-10-2021',
    environment_score: 500,
    social_score: 300,
    governance_score: 305,
    total: 1105
  },
  {
    esg_id: 121,
    company_name: 'Adobe Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'ADBE',
    environment_grade: 'B',
    environment_level: 'Medium',
    social_grade: 'B',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'B',
    total_level: 'Medium',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '01-10-2021',
    environment_score: 240,
    social_score: 200,
    governance_score: 200,
    total: 640
  },
  {
    esg_id: 1766,
    company_name: 'Comcast Corporation',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'CMCSA',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '02-10-2021',
    environment_score: 530,
    social_score: 362,
    governance_score: 300,
    total: 1192
  },
  {
    esg_id: 5007,
    company_name: 'NetEase, Inc.',
    exchange_symbol: 'OTCMKTS',
    stock_symbol: 'NTES',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-09-2021',
    environment_score: 500,
    social_score: 274,
    governance_score: 305,
    total: 1079
  },
  {
    esg_id: 5562,
    company_name: 'PepsiCo, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'PEP',
    environment_grade: 'AA',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'A',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-09-2021',
    environment_score: 613,
    social_score: 363,
    governance_score: 315,
    total: 1291
  },
  {
    esg_id: 1168,
    company_name: 'Broadcom Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'AVGO',
    environment_grade: 'BB',
    environment_level: 'Medium',
    social_grade: 'B',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'B',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '02-10-2021',
    environment_score: 270,
    social_score: 225,
    governance_score: 225,
    total: 720
  },
  {
    esg_id: 1927,
    company_name: 'Costco Wholesale Corporation',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'COST',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '02-10-2021',
    environment_score: 535,
    social_score: 311,
    governance_score: 210,
    total: 1056
  },
  {
    esg_id: 70490,
    company_name: 'AstraZeneca PLC',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'AZN',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '30-09-2021',
    environment_score: 500,
    social_score: 300,
    governance_score: 300,
    total: 1100
  },
  {
    esg_id: 7020,
    company_name: 'Texas Instruments Incorporated',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'TXN',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '14-09-2021',
    environment_score: 482,
    social_score: 287,
    governance_score: 260,
    total: 1029
  },
  {
    esg_id: 7096,
    company_name: 'T-Mobile US, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'TMUS',
    environment_grade: 'BBB',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'BB',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '14-09-2021',
    environment_score: 337,
    social_score: 306,
    governance_score: 220,
    total: 863
  },
  {
    esg_id: 1493,
    company_name: 'Charter Communications, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'CHTR',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '02-10-2021',
    environment_score: 500,
    social_score: 300,
    governance_score: 300,
    total: 1100
  },
  {
    esg_id: 3548,
    company_name: 'Honeywell International Inc.',
    exchange_symbol: 'NYSE',
    stock_symbol: 'HON',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '12-09-2021',
    environment_score: 513,
    social_score: 304,
    governance_score: 300,
    total: 1117
  },
  {
    esg_id: 3864,
    company_name: 'Intuit Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'INTU',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'A',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-09-2021',
    environment_score: 560,
    social_score: 340,
    governance_score: 305,
    total: 1205
  },
  {
    esg_id: 5909,
    company_name: 'QUALCOMM Incorporated',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'QCOM',
    environment_grade: 'BBB',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '14-09-2021',
    environment_score: 399,
    social_score: 300,
    governance_score: 300,
    total: 999
  },
  {
    esg_id: 4512,
    company_name: 'Moderna, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'MRNA',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-09-2021',
    environment_score: 410,
    social_score: 300,
    governance_score: 300,
    total: 1010
  },
  {
    esg_id: 6701,
    company_name: 'Starbucks Corporation',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'SBUX',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '14-09-2021',
    environment_score: 480,
    social_score: 353,
    governance_score: 275,
    total: 1108
  },
  {
    esg_id: 132,
    company_name: 'Advanced Micro Devices, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'AMD',
    environment_grade: 'B',
    environment_level: 'Medium',
    social_grade: 'B',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'B',
    total_level: 'Medium',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '02-10-2021',
    environment_score: 205,
    social_score: 214,
    governance_score: 200,
    total: 619
  },
  {
    esg_id: 3678,
    company_name: 'Illumina, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'ILMN',
    environment_grade: 'BBB',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '12-09-2021',
    environment_score: 340,
    social_score: 301,
    governance_score: 330,
    total: 971
  },
  {
    esg_id: 432,
    company_name: 'Amgen Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'AMGN',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '02-10-2021',
    environment_score: 505,
    social_score: 325,
    governance_score: 300,
    total: 1130
  },
  {
    esg_id: 508,
    company_name: 'Applied Materials, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'AMAT',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '02-10-2021',
    environment_score: 540,
    social_score: 311,
    governance_score: 300,
    total: 1151
  },
  {
    esg_id: 3979,
    company_name: 'JD.com, Inc.',
    exchange_symbol: 'OTCMKTS',
    stock_symbol: 'JD',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-09-2021',
    environment_score: 500,
    social_score: 258,
    governance_score: 305,
    total: 1063
  },
  {
    esg_id: 3950,
    company_name: 'J.B. Hunt Transport Services, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'JBHT',
    environment_grade: 'AA',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'A',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-09-2021',
    environment_score: 622,
    social_score: 394,
    governance_score: 303,
    total: 1319
  },
  {
    esg_id: 70346,
    company_name: 'Airbnb, Inc',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'ABNB',
    environment_grade: 'B',
    environment_level: 'Medium',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'B',
    total_level: 'Medium',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '30-09-2021',
    environment_score: 205,
    social_score: 266,
    governance_score: 210,
    total: 681
  },
  {
    esg_id: 70522,
    company_name: 'Booking Holdings Inc',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'BKNG',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '30-09-2021',
    environment_score: 505,
    social_score: 300,
    governance_score: 315,
    total: 1120
  },
  {
    esg_id: 668,
    company_name: 'Atlassian Corporation Plc',
    exchange_symbol: 'OTCMKTS',
    stock_symbol: 'TEAM',
    environment_grade: 'BBB',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '02-10-2021',
    environment_score: 370,
    social_score: 399,
    governance_score: 323,
    total: 1092
  },
  {
    esg_id: 3092,
    company_name: 'Gilead Sciences, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'GILD',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '12-09-2021',
    environment_score: 510,
    social_score: 320,
    governance_score: 325,
    total: 1155
  },
  {
    esg_id: 713,
    company_name: 'Automatic Data Processing, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'ADP',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '02-10-2021',
    environment_score: 505,
    social_score: 303,
    governance_score: 300,
    total: 1108
  },
  {
    esg_id: 4646,
    company_name: 'MercadoLibre, Inc.',
    exchange_symbol: 'BCBA',
    stock_symbol: 'MELI',
    environment_grade: 'B',
    environment_level: 'Medium',
    social_grade: 'B',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'B',
    total_level: 'Medium',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-09-2021',
    environment_score: 205,
    social_score: 214,
    governance_score: 210,
    total: 629
  },
  {
    esg_id: 4816,
    company_name: 'Mondelez International, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'MDLZ',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BBB',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-09-2021',
    environment_score: 505,
    social_score: 321,
    governance_score: 310,
    total: 1136
  },
  {
    esg_id: 4214,
    company_name: 'Lam Research Corporation',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'LRCX',
    environment_grade: 'A',
    environment_level: 'Medium',
    social_grade: 'BBB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'A',
    total_level: 'Excellent',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-09-2021',
    environment_score: 567,
    social_score: 346,
    governance_score: 305,
    total: 1218
  },
  {
    esg_id: 4716,
    company_name: 'Micron Technology, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'MU',
    environment_grade: 'B',
    environment_level: 'Medium',
    social_grade: 'B',
    social_level: 'Medium',
    governance_grade: 'B',
    governance_level: 'Medium',
    total_grade: 'B',
    total_level: 'Medium',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '13-09-2021',
    environment_score: 200,
    social_score: 202,
    governance_score: 200,
    total: 602
  },
  {
    esg_id: 71763,
    company_name: 'Zoom Video Communications, Inc.',
    exchange_symbol: 'NASDAQ',
    stock_symbol: 'ZM',
    environment_grade: 'BB',
    environment_level: 'Medium',
    social_grade: 'BB',
    social_level: 'Medium',
    governance_grade: 'BBB',
    governance_level: 'Medium',
    total_grade: 'BB',
    total_level: 'High',
    disclaimer:
      'ESG Enterprise\u0027s ESG Rating data (\u0022Scores\u0022) are all based on public information and provided for informational purposes only. No member of ESG Enterprise or related parties make any prediction, warranty or representation whatsoever, expressly or impliedly, either as to the suitability of our Scores for any particular purposes or the validity of any derivative analysis or conclusion based on the Scores.',
    last_processing_date: '01-10-2021',
    environment_score: 250,
    social_score: 293,
    governance_score: 300,
    total: 843
  }
]
